- name: Kubeadm reset
  shell: kubeadm reset -f >> reset.log
  args:
    chdir: $HOME
    creates: reset.log

- name: Join master to cluster
  shell: "{{ hostvars[groups['masters'][0]]['join_master_command'] }} >> other_masters.log"
  ignore_errors: yes
  args:
    chdir: $HOME
    creates: other_masters.log
