- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install required packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - python3-minimal
      - curl 
      - wget
      - python3-pip
