- name: Initialize Kubernetes Cluster
  shell: kubeadm init --pod-network-cidr 10.244.0.0/16 --service-dns-domain "apps.aon360sdm.local" --control-plane-endpoint "lb.aon360sdm.local" --ignore-preflight-errors=NumCPU --upload-certs >> cluster_init.log
  args:
    chdir: $HOME
    creates: cluster_init.log

- name: Create .kube directory
  file: 
    path: $HOME/.kube
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Copy default cluster configuration
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0660    

- name: Change config mode
  file:
    path: $HOME/.kube/config
    state: file
    owner: root
    group: root 
    mode: 0660

- name: Put template kubelet file
  template: 
    src: kubelet-config.yml.j2
    dest: /var/lib/kubelet/config.yaml
    owner: root
    group: root 
    mode: 0777
