- name: "Create token to join cluster"
  shell: kubeadm token create --print-join-command
  register: join_command_raw
- debug: msg="join command is {{ join_command_raw.stdout }}"

- name: "Set join command as fact"
  set_fact: join_command="{{ join_command_raw.stdout }}"

- name: "Create a new certificate key"
  become: true
  command: kubeadm init phase upload-certs --upload-certs
  register: join_certificate_key

- name: "Generate master join command"
  become: true
  command: kubeadm token create --print-join-command --certificate-key "{{ join_certificate_key.stdout_lines[2] }}"
  register: join_master_command_raw
- debug: msg="join command is {{ join_master_command_raw.stdout }}"

- name: "Set join master command as fact"
  set_fact: join_master_command="{{ join_master_command_raw.stdout }}"
